changelog:
    exclude:
        authors:
            - dependabot
            - dependabot[bot]
    categories:
        - title: Breaking Changes
          labels:
              - '[Type] Breaking Change'
        - title: Features & Enhancements
          labels:
              - '[Type] Enhancement'
        - title: Bug Fixes
          labels:
              - '[Type] Bug'
              - '[Type] Regression'
        - title: Other Changes
          labels:
              - '*'
