import groovy.json.JsonSlurper
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Generates `SupportedLocales.kt` from the JS-build manifest so the set of
 * shipped locales is checked at compile time, not at runtime. Run `make build`
 * from the repo root to populate `src/main/assets/supported-locales.json`
 * before assembling the library.
 *
 * The output is handed to AGP's `sources.kotlin.addGeneratedSourceDirectory`,
 * which wires the task dependency for every consumer of the source set
 * (compilation plus the source jars for publishing).
 */
abstract class GenerateSupportedLocales : DefaultTask() {
    /**
     * Declared as a file *collection* rather than an `@InputFile` so a missing
     * manifest doesn't trip Gradle's strict input validation before the more
     * actionable error below can surface.
     */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val manifest: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val manifestFile = manifest.singleFile
        if (!manifestFile.exists()) {
            throw GradleException(
                "supported-locales.json is missing from src/main/assets/. " +
                    "Run `make build` from the repo root to populate translation " +
                    "assets before assembling the :Gutenberg library."
            )
        }

        val parsed = JsonSlurper().parse(manifestFile) as? List<*>
            ?: throw GradleException(
                "supported-locales.json is not a JSON array. Re-run `make build`."
            )
        val locales = parsed.map {
            it as? String ?: throw GradleException(
                "supported-locales.json contains a non-string entry: $it. Re-run `make build`."
            )
        }.sorted()

        if (locales.isEmpty()) {
            // An empty manifest typically means `make prep-translations` was
            // skipped or failed silently — `src/translations/` only had
            // `.gitkeep` when Vite scanned it. Without this guard the library
            // ships with a runtime-empty `SupportedLocales`, which resolves
            // every locale to English.
            throw GradleException(
                "supported-locales.json is empty. Run `make prep-translations REFRESH_L10N=1` " +
                    "from the repo root, then `make build`, before assembling the :Gutenberg library."
            )
        }

        val outDir = outputDirectory.get().asFile
            .resolve("org/wordpress/gutenberg/model")
            .also { it.mkdirs() }
        outDir.resolve("SupportedLocales.kt").writeText(buildString {
            appendLine("// Generated by :Gutenberg:generateSupportedLocales — do not edit.")
            appendLine("package org.wordpress.gutenberg.model")
            appendLine()
            appendLine("internal object SupportedLocales {")
            appendLine("    val ALL: Set<String> = setOf(")
            locales.forEach { appendLine("        \"$it\",") }
            appendLine("    )")
            appendLine("}")
        })
    }
}
