// This file is auto-generated by bin/generate-version.js
// Do not edit manually - changes will be overwritten

/// GutenbergKit version information.
public enum GutenbergKitVersion {
    /// The current version of GutenbergKit.
    public static let version = "0.19.0-alpha.0"
}
