// This file is auto-generated by bin/generate-version.js
// Do not edit manually - changes will be overwritten

extension GutenbergKit {
    /// The GutenbergKit version string
    public static let version = "0.11.1"
}
