agents:
  queue: mac

env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: ":react: Build React App"
    command: make build
    plugins: &plugins
      - $CI_TOOLKIT_PLUGIN
      - $NVM_PLUGIN

  - label: ":android: Publish Android Library"
    command: |
      make build
      echo "--- :android: Publishing Android Library"
      ./Demo-Android/gradlew -p Demo-Android :gutenberg:prepareToPublishToS3 $(prepare_to_publish_to_s3_params) :gutenberg:publish
    agents:
      queue: android
    plugins: *plugins
      - $CI_TOOLKIT_PLUGIN
      - $NVM_PLUGIN

  - label: ":swift: Build Swift Package"
    command: make build_swift_package
    plugins: *plugins
