agents:
    queue: mac

env:
    IMAGE_ID: $IMAGE_ID

steps:
    - label: ':javascript: Test JavaScript'
      command: make test-js
      plugins: *plugins

    - label: ':swift: Test Swift Package'
      # With the HTML assets in the GutenbergKitResources package and ignored by Git, we need to generated on demand for the moment
      command: make build && swift test
      plugins: *plugins
