agents:
  queue: mac

env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: ":swift: Build Swift Package"
    command: make build_swift_package
    plugins: &plugins
      - $CI_TOOLKIT_PLUGIN
      - $NVM_PLUGIN

  - label: ":react: Build React App"
    command: make build
    plugins: *plugins
