// This file is auto-generated by bin/generate-version.js
// Do not edit manually - changes will be overwritten

package org.wordpress.gutenberg

/**
 * GutenbergKit version information.
 */
object GutenbergKitVersion {
    /**
     * The current version of GutenbergKit.
     */
    const val VERSION = "0.19.0-alpha.0"
}
