// This file is auto-generated by bin/generate-version.js
// Do not edit manually - changes will be overwritten

package org.wordpress.gutenberg

/**
 * GutenbergKit version information
 */
object GutenbergKitVersion {
    /**
     * The GutenbergKit version string
     */
    const val VERSION = "0.11.1"
}
