// This file is auto-generated by bin/generate-version.js
// Do not edit manually - changes will be overwritten

package org.wordpress.gutenberg

/**
 * GutenbergKit library constants and utilities.
 */
object GutenbergKit {
    /**
     * The current version of GutenbergKit.
     */
    const val VERSION = "0.11.1"
}
