# frozen_string_literal: true

source "https://rubygems.org"

# Let the release-toolkit drive which Fastlane version to use.
# See also https://github.com/wordpress-mobile/release-toolkit/issues/482
gem 'fastlane'
gem 'fastlane-plugin-wpmreleasetoolkit', '~> 9.1.0'
