import Foundation

/// Reads `supported-locales.json` (a JSON array of locale tags emitted by the
/// Vite build) and writes a Swift source file declaring an
/// `internal enum SupportedLocales { static let all: Set<String> }` constant.
///
/// Invoked by `SupportedLocalesPlugin` as a buildCommand; not intended to be
/// run directly.
@main
struct GenerateSupportedLocales {
    static func main() {
        let args = CommandLine.arguments
        guard args.count == 3 else {
            fail("usage: GenerateSupportedLocales <manifest.json> <output.swift>")
        }

        let manifestURL = URL(fileURLWithPath: args[1])
        let outputURL = URL(fileURLWithPath: args[2])

        guard FileManager.default.fileExists(atPath: manifestURL.path) else {
            fail(
                "missing supported-locales manifest at \(manifestURL.path). "
                + "Run `make build` to regenerate it."
            )
        }

        let data: Data
        do {
            data = try Data(contentsOf: manifestURL)
        } catch {
            fail("could not read \(manifestURL.path): \(error.localizedDescription)")
        }

        let locales: [String]
        do {
            locales = try JSONDecoder().decode([String].self, from: data)
        } catch {
            fail(
                "manifest at \(manifestURL.path) is not a JSON array of strings: "
                + "\(error.localizedDescription)"
            )
        }

        let entries = Set(locales).sorted()
            .map { "        \"\($0)\"" }
            .joined(separator: ",\n")

        let source = """
            // Generated by SupportedLocalesPlugin from supported-locales.json.
            // Do not edit.

            internal enum SupportedLocales {
                static let all: Set<String> = [
            \(entries)
                ]
            }

            """

        do {
            try source.write(to: outputURL, atomically: true, encoding: .utf8)
        } catch {
            fail("could not write \(outputURL.path): \(error.localizedDescription)")
        }
    }

    private static func fail(_ message: String) -> Never {
        FileHandle.standardError.write(Data("error: \(message)\n".utf8))
        exit(1)
    }
}
