# frozen_string_literal: true

PROJECT_ROOT = File.expand_path('..', __dir__)

LANE_VALUE_VERSION = 'GBK_VERSION'
LANE_VALUE_GITHUB_TOKEN = 'GBK_GITHUB_TOKEN'

GITHUB_REPO = 'wordpress-mobile/GutenbergKit'
GIT_REMOTE_NAME = 'origin'
GIT_BASE_BRANCH = 'trunk'

# Code Signing
APPLE_TEAM_ID = 'PZYM8XX95Q'

ASC_API_KEY_ENV_VARS = %w[
  APP_STORE_CONNECT_API_KEY_KEY_ID
  APP_STORE_CONNECT_API_KEY_ISSUER_ID
  APP_STORE_CONNECT_API_KEY_KEY
].freeze

CODE_SIGNING_STORAGE_ENV_VARS = %w[
  MATCH_S3_ACCESS_KEY
  MATCH_S3_SECRET_ACCESS_KEY
].freeze

before_all do
  setup_ci
end

# --------------------------------------------------------------------------
# Release lane
# --------------------------------------------------------------------------

lane :release do |options|
  version = options[:version] || UI.user_error!('version is required')
  lane_context[LANE_VALUE_VERSION] = version

  github_token = ENV['GITHUB_TOKEN'] || UI.user_error!('GITHUB_TOKEN env var is required')
  lane_context.set_sensitive(LANE_VALUE_GITHUB_TOKEN, github_token)

  validate
  update_swift_package
  publish_release_to_github
  publish_to_s3
end

# --------------------------------------------------------------------------
# Individual lanes
# --------------------------------------------------------------------------

lane :validate do
  version = lane_context[LANE_VALUE_VERSION] || UI.user_error!('Missing version lane context')
  github_token = lane_context[LANE_VALUE_GITHUB_TOKEN] || UI.user_error!('Missing github token lane context')

  UI.user_error!("Release #{version} already exists in the GitHub repo") \
    unless get_github_release(url: GITHUB_REPO, version: version, api_token: github_token).nil?
  remove_lane_context_values [
    SharedValues::GITHUB_API_RESPONSE,
    SharedValues::GITHUB_API_STATUS_CODE,
    SharedValues::GITHUB_API_JSON
  ]

  UI.user_error!("Tag #{version} already exists in the GitHub repo") \
    if git_tag_exists(tag: version, remote: true, remote_name: GIT_REMOTE_NAME)
end

lane :update_swift_package do
  version = lane_context[LANE_VALUE_VERSION] || UI.user_error!('Missing version lane context')

  file_path = File.expand_path('./Package.swift', PROJECT_ROOT)
  lines = File.readlines(file_path).map do |line|
    if line.start_with?('let resourcesVersion =')
      "let resourcesVersion = \"#{version}\"\n"
    elsif line.start_with?('let resourcesChecksum =')
      "let resourcesChecksum = \"#{xcframework_checksum}\"\n"
    else
      line
    end
  end
  File.open(file_path, 'w') { |file| file.print lines.join }
end

lane :publish_release_to_github do
  version = lane_context[LANE_VALUE_VERSION] || UI.user_error!('Missing version lane context')
  github_token = lane_context[LANE_VALUE_GITHUB_TOKEN] || UI.user_error!('Missing github token lane context')

  sh "git checkout -b release/#{version}"
  git_commit(
    path: File.expand_path('./Package.swift', PROJECT_ROOT),
    message: "Update Package.swift to use version #{version}"
  )

  add_git_tag(tag: version)
  push_git_tags(tag: version, remote: GIT_REMOTE_NAME)
  set_github_release(
    api_token: github_token,
    repository_name: GITHUB_REPO,
    name: version,
    tag_name: version,
    description: "Release version #{version}",
    upload_assets: [xcframework_file_path, xcframework_checksum_file_path]
  )
end

lane :publish_to_s3 do
  version = lane_context[LANE_VALUE_VERSION] || UI.user_error!('Missing version lane context')

  upload_to_s3(
    bucket: 'a8c-apps-public-artifacts',
    key: File.join('gutenbergkit', version, File.basename(xcframework_file_path)),
    file: xcframework_file_path,
    auto_prefix: false,
    if_exists: :fail
  )

  upload_to_s3(
    bucket: 'a8c-apps-public-artifacts',
    key: File.join('gutenbergkit', version, File.basename(xcframework_checksum_file_path)),
    file: xcframework_checksum_file_path,
    auto_prefix: false,
    if_exists: :fail
  )
end

lane :xcframework_sign do
  require_env_vars!(*ASC_API_KEY_ENV_VARS, *CODE_SIGNING_STORAGE_ENV_VARS)

  set_up_signing_release

  sh(
    'codesign',
    '--timestamp',
    '-s', 'Apple Distribution',
    xcframework_file_path.sub('.zip', '')
  )
end

desc 'Download the release (distribution) signing certificates'
lane :set_up_signing_release do |readonly: true|
  require_env_vars!(*ASC_API_KEY_ENV_VARS, *CODE_SIGNING_STORAGE_ENV_VARS)

  sync_code_signing(
    team_id: APPLE_TEAM_ID,
    api_key: app_store_connect_api_key,
    type: 'appstore',
    storage_mode: 's3',
    s3_region: 'us-east-2',
    s3_bucket: 'a8c-fastlane-match',
    readonly: readonly,
    app_identifier: 'com.automattic.hostmgr',
    platform: 'macos'
  )
end

# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------

def xcframework_checksum
  File.read(xcframework_checksum_file_path).strip
end

def xcframework_checksum_file_path
  Dir.glob(File.join(PROJECT_ROOT, 'GutenbergKitResources-*.xcframework.zip.checksum.txt')).first \
    || UI.user_error!('XCFramework checksum file not found. Run build_xcframework.sh first.')
end

def xcframework_file_path
  Dir.glob(File.join(PROJECT_ROOT, 'GutenbergKitResources-*.xcframework.zip')).first \
    || UI.user_error!('XCFramework zip not found. Run build_xcframework.sh first.')
end

def remove_lane_context_values(names)
  names.each { |name| lane_context.delete(name) }
end

def require_env_vars!(*keys)
  keys.each { |key| get_required_env!(key) }
end

def get_required_env!(key)
  return ENV.fetch(key) if ENV.key?(key)

  UI.user_error!("Environment variable `#{key}` is not set.")
end
