# frozen_string_literal: true

require 'zip'

before_all do
  # Ensure we use the latest version of the toolkit
  check_for_toolkit_updates unless is_ci || ENV['FASTLANE_SKIP_TOOLKIT_UPDATE_CHECK']
end

lane :upload_ios_artifacts_to_s3 do
  artifacts_path = File.join(Dir.pwd, '../Sources/GutenbergKit/Gutenberg')

  unless File.directory?(artifacts_path)
    UI.user_error!("Could not find artifacts to upload at '#{artifacts_path}'.")
  end

  zipfile_name = "#{artifacts_path}.zip"

  Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
    Dir[File.join(artifacts_path, '**', '**')].each do |file|
      zipfile.add(file.sub(artifacts_path + '/', ''), file)
    end
  end

  upload_artifact_files_to_s3(archive_path: zipfile_name, id: last_git_commit[:commit_hash])

  next unless is_ci

  tag = ENV.fetch('BUILDKITE_TAG', nil)

  next if tag.nil? || tag.empty?

  # Tradeoff: We are "wasting" space on S3 by uploading the same archive under different name.
  # What we get in return is a 1-1 correspondency between archive and podspec, which keeps the setup simpler.
  upload_artifact_files_to_s3(archive_path: zipfile_name, id: tag)
end

def upload_artifact_files_to_s3(archive_path:, id:)
  upload_to_a8c_s3(file: archive_path, name_on_s3: "gutenberg-kit-resources-#{id}.zip")
end

# Notice skip_if_exists is true by default.
# CI might run on the same commit twice, once for the commit and once for the tag.
# We don't want to fail on the second run.
def upload_to_a8c_s3(file:, name_on_s3:, prefix: 'gutenberg-kit')
  upload_to_s3(
    bucket: 'a8c-apps-public-artifacts',
    key: "#{prefix}/#{name_on_s3}",
    file: file,
    auto_prefix: false,
    if_exists: :skip,
  )
end
