import groovy.json.JsonSlurper

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.jetbrains.kotlin.android)
    alias(libs.plugins.jetbrains.kotlin.compose)
    alias(libs.plugins.jetbrains.kotlin.serialization)
    id("com.automattic.android.publish-to-s3")
    id("kotlin-parcelize")
}

// Generates `SupportedLocales.kt` from the JS-build manifest so the set of
// shipped locales is checked at compile time, not at runtime. Run `make
// build` from the repo root to populate `src/main/assets/supported-locales.json`
// before assembling the library.
//
// Registered above `android { ... }` so the `main` source set can reference
// `generatedLocalesDir` directly. AGP's source-set DSL only accepts
// path-shaped notations (String / File / Path / Directory) for `srcDir`,
// so the task→consumer dependency is wired explicitly below for every
// consumer of the source set (compile + source jars for publishing).
val supportedLocalesManifest = layout.projectDirectory.file("src/main/assets/supported-locales.json")
val generatedLocalesDir = layout.buildDirectory.dir("generated/source/locales/main")

val generateSupportedLocales = tasks.register("generateSupportedLocales") {
    description = "Generates SupportedLocales.kt from the shipped translation manifest."
    group = "build"

    // Use `inputs.files(...)` (plural) instead of `inputs.file(...)` so a
    // missing manifest doesn't trip Gradle's strict input validation before
    // our own error message can surface.
    inputs.files(supportedLocalesManifest)
        .withPropertyName("manifest")
        .withPathSensitivity(PathSensitivity.RELATIVE)
    outputs.dir(generatedLocalesDir)

    doFirst {
        if (!supportedLocalesManifest.asFile.exists()) {
            throw GradleException(
                "supported-locales.json is missing from src/main/assets/. " +
                    "Run `make build` from the repo root to populate translation " +
                    "assets before assembling the :Gutenberg library."
            )
        }
    }

    doLast {
        val manifest = supportedLocalesManifest.asFile

        val parsed = JsonSlurper().parse(manifest) as? List<*>
            ?: throw GradleException(
                "supported-locales.json is not a JSON array. Re-run `make build`."
            )
        val locales = parsed.map {
            it as? String ?: throw GradleException(
                "supported-locales.json contains a non-string entry: $it. Re-run `make build`."
            )
        }.sorted()

        if (locales.isEmpty()) {
            // An empty manifest typically means `make prep-translations` was
            // skipped or failed silently — `src/translations/` only had
            // `.gitkeep` when Vite scanned it. Without this guard the
            // library ships with a runtime-empty `SupportedLocales`, which
            // resolves every locale to English.
            throw GradleException(
                "supported-locales.json is empty. Run `make prep-translations REFRESH_L10N=1` " +
                    "from the repo root, then `make build`, before assembling the :Gutenberg library."
            )
        }

        val outDir = generatedLocalesDir.get().asFile
            .resolve("org/wordpress/gutenberg/model")
            .also { it.mkdirs() }
        outDir.resolve("SupportedLocales.kt").writeText(buildString {
            appendLine("// Generated by :Gutenberg:generateSupportedLocales — do not edit.")
            appendLine("package org.wordpress.gutenberg.model")
            appendLine()
            appendLine("internal object SupportedLocales {")
            appendLine("    val ALL: Set<String> = setOf(")
            locales.forEach { appendLine("        \"$it\",") }
            appendLine("    )")
            appendLine("}")
        })
    }
}

android {
    namespace = "org.wordpress.gutenberg"
    compileSdk = 34
    resourcePrefix = "gbk_"

    buildFeatures {
        buildConfig = true
        compose = true
    }

    defaultConfig {
        minSdk = 24

        buildConfigField(
            "String",
            "GUTENBERG_EDITOR_URL",
            "\"${rootProject.ext["gutenbergEditorUrl"] ?: ""}\""
        )

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        configureBuildkiteTestCollector(
            testInstrumentationRunnerArguments,
            "BUILDKITE_ANALYTICS_TOKEN_ANDROID_LIBRARY_E2E",
        )

        consumerProguardFiles("consumer-rules.pro")
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }

    sourceSets {
        getByName("main") {
            java.srcDir(generatedLocalesDir)
        }
        getByName("androidTest") {
            // Make shared test fixtures available as assets for instrumented tests.
            assets.srcDir(rootProject.file("../test-fixtures"))
        }
    }

    testOptions {
        unitTests {
            isReturnDefaultValues = true
            all {
                // Make the shared test fixtures available to fixture-driven tests.
                val fixturesDir = rootProject.file("../test-fixtures/http")
                it.systemProperty("test.fixtures.dir", fixturesDir.absolutePath)
                // Track fixture files as task inputs so changes trigger re-runs.
                it.inputs.dir(fixturesDir)
            }
        }
    }
}

dependencies {

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.webkit)
    implementation(libs.gson)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.jsoup)
    implementation(libs.okhttp)
    implementation(libs.androidsvg)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.activity.compose)

    testImplementation(libs.json)
    testImplementation(libs.junit)
    testImplementation(kotlin("test"))
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.mockito.core)
    testImplementation(libs.mockito.kotlin)
    testImplementation(libs.robolectric)
    testImplementation(libs.okhttp.mockwebserver)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.buildkite.test.collector.instrumented)
    androidTestImplementation(kotlin("test"))
}

project.afterEvaluate {
    publishing {
        publications {
            create<MavenPublication>("maven") {
                from(components["release"])

                groupId = "org.wordpress.gutenbergkit"
                artifactId = "android"
                // version is set by 'publish-to-s3' plugin
            }
        }
    }
}

// Wire the generator into every task that reads the `main` source set's
// sources: Kotlin compilation and the source-jar tasks AGP creates for the
// maven publication. AGP's source-set DSL only accepts a path string for
// `srcDir`, so the dependency can't be inferred from the source set itself.
tasks.matching {
    val name = it.name
    (name.startsWith("compile") && name.endsWith("Kotlin")) ||
        (name.startsWith("source") && name.endsWith("Jar"))
}.configureEach { dependsOn(generateSupportedLocales) }

